import { AlertCircle, Bell, CheckCircle2, ChevronLeft, ClipboardList, Clock3, MapPin, PlayCircle, ShieldAlert, Truck } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { Text } from '@/components/ui/Text';
import { ErrorState, LoadingState } from '@/components/ui/States';
import { colors, elevation, layout, radius, spacing } from '@/theme/tokens';
import { fetchNotifications, markAllNotificationsRead, markNotificationRead, type AppNotification } from '@/services/notifications';

const iconMap = { info: ClipboardList, success: CheckCircle2, warning: Clock3, danger: AlertCircle } as const;
const colorMap = { info: colors.brand, success: colors.success, warning: colors.warning, danger: colors.dangerStrong } as const;

export default function NotificationsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [items, setItems] = useState<AppNotification[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { setItems(await fetchNotifications()); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível carregar as notificações.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const unread = useMemo(() => items.filter((item) => !item.read_at).length, [items]);
  async function openItem(item: AppNotification) { if (!item.read_at) { await markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, read_at: new Date().toISOString() } : entry)); } const callId = typeof item.data?.call_id === 'string' ? item.data.call_id : null; if (callId) router.push(`/chamado/${callId}`); }
  async function readAll() { await markAllNotificationsRead(); setItems((current) => current.map((item) => ({ ...item, read_at: new Date().toISOString() }))); }
  return <View style={styles.root}><View style={[styles.header, { paddingTop: insets.top + spacing.lg }]}><Pressable onPress={() => router.back()} style={styles.back}><ChevronLeft size={21} color={colors.textOnBrand} /></Pressable><View style={styles.headerText}><Text variant="screenTitle" color={colors.textOnBrand}>Notificações</Text><Text variant="body" color={colors.slate200}>Atualizações dos seus serviços</Text></View><Bell size={22} color={colors.textOnBrand} /></View><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={colors.brand} />} contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.xxl }]}>{unread > 0 ? <Pressable onPress={() => { void readAll(); }} style={styles.readAll}><Text variant="meta" color={colors.brand}>MARCAR TODAS COMO LIDAS ({unread})</Text></Pressable> : null}{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : items.length === 0 ? <View style={styles.empty}><Bell size={30} color={colors.textMuted} /><Text variant="bodyStrong">Nenhuma notificação</Text><Text variant="body" color={colors.textSecondary}>Atualizações importantes aparecerão aqui.</Text></View> : items.map((item) => <NotificationCard key={item.id} item={item} onPress={() => { void openItem(item); }} />)}</ScrollView></View>;
}
function NotificationCard({ item, onPress }: { item: AppNotification; onPress: () => void }) { const Icon = iconMap[item.kind] ?? Bell; const color = colorMap[item.kind] ?? colors.brand; return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, !item.read_at && styles.unread, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: `${color}15`, borderColor: `${color}25` }]}><Icon size={21} color={color} /></View><View style={styles.cardBody}><View style={styles.cardTop}><Text variant="bodyStrong" numberOfLines={1} style={styles.cardTitle}>{item.title}</Text><Text variant="meta" color={item.read_at ? colors.textMuted : color}>{formatDate(item.created_at)}</Text></View><Text variant="body" color={colors.textSecondary}>{item.body ?? 'Atualização disponível no sistema.'}</Text></View>{!item.read_at ? <View style={[styles.dot, { backgroundColor: color }]} /> : null}</Pressable>; }
function formatDate(value: string) { const date = new Date(value); const today = new Date(); if (date.toDateString() === today.toDateString()) return date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }); return date.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' }); }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bgApp }, header: { backgroundColor: colors.brandStrong, paddingHorizontal: layout.screenPadding, paddingBottom: spacing.xxl, borderBottomLeftRadius: 40, borderBottomRightRadius: 40, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, back: { width: 42, height: 42, borderRadius: radius.lg, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' }, headerText: { flex: 1, gap: spacing.xs }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: layout.screenPadding, gap: spacing.md }, readAll: { alignSelf: 'flex-end', paddingVertical: spacing.xs }, card: { backgroundColor: colors.bgSurface, borderWidth: 1, borderColor: colors.border, borderRadius: 28, padding: spacing.lg, flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, ...elevation.card }, unread: { borderColor: colors.brandSoft }, icon: { width: 48, height: 48, borderRadius: radius.pill, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, cardBody: { flex: 1, gap: spacing.xs }, cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, cardTitle: { flex: 1 }, dot: { width: 8, height: 8, borderRadius: radius.pill, marginTop: spacing.xs }, empty: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xxl }, pressed: { opacity: 0.78, transform: [{ scale: 0.99 }] } });
