import { Camera, ChevronLeft, Image as ImageIcon, Plus, Save, X } from 'lucide-react-native';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { Text } from '@/components/ui/Text';
import { Button } from '@/components/ui/Button';
import { ErrorState, LoadingState } from '@/components/ui/States';
import { captureAndUploadPhoto, fetchServicePhotos, fetchTechnicianCall, pickAndUploadPhoto, type TechnicianCall, type TechnicianPhoto } from '@/services/technician';
import { supabase } from '@/lib/supabase';
import { colors, elevation, fonts, layout, radius, spacing } from '@/theme/tokens';

export default function PhotoRegistrationScreen() { const router = useRouter(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const [call, setCall] = useState<TechnicianCall | null>(null); const [photos, setPhotos] = useState<TechnicianPhoto[]>([]); const [stage, setStage] = useState<TechnicianPhoto['stage']>('antes'); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { if (!id) return; try { const serviceCall = await fetchTechnicianCall(id); setCall(serviceCall); setPhotos(await fetchServicePhotos(id)); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível carregar as fotos.'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]); const currentPhotos = useMemo(() => photos.filter((photo) => photo.stage === stage), [photos, stage]); async function addPhoto(mode: 'camera' | 'gallery') { if (!call) return; setBusy(true); setError(null); try { const photo = mode === 'camera' ? await captureAndUploadPhoto(call, stage) : await pickAndUploadPhoto(call, stage); if (photo) setPhotos((current) => [...current, photo]); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível salvar a foto.'); } finally { setBusy(false); } } function imageUri(path: string) { return supabase.storage.from('service-photos').getPublicUrl(path).data.publicUrl; } async function save() { if (!photos.some((photo) => photo.stage === 'antes') || !photos.some((photo) => photo.stage === 'depois')) { Alert.alert('Evidência obrigatória', 'Registre pelo menos uma foto antes e uma foto depois do serviço.'); return; } Alert.alert('Registro salvo', 'As evidências estão vinculadas à ordem de serviço.', [{ text: 'Concluir', onPress: () => router.back() }]); }
  return <View style={styles.root}><View style={[styles.header, { paddingTop: insets.top + spacing.lg }]}><Pressable onPress={() => router.back()} style={styles.back}><ChevronLeft size={21} color={colors.textOnBrand} /></Pressable><View style={styles.headerText}><Text variant="screenTitle" color={colors.textOnBrand}>Registro Fotográfico</Text><Text variant="body" color={colors.slate200}>Documente o serviço realizado</Text></View></View>{loading ? <LoadingState /> : error && !call ? <ErrorState message={error} onRetry={load} /> : <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.xxl }]}><View style={styles.tabs}>{(['antes', 'depois', 'durante'] as const).map((item) => <Pressable key={item} onPress={() => setStage(item)} style={[styles.tab, stage === item && styles.tabActive]}><Text variant="meta" color={stage === item ? colors.brand : colors.textMuted}>{item === 'antes' ? 'Antes do serviço' : item === 'depois' ? 'Depois do serviço' : 'Adicionais'}</Text></Pressable>)}</View><View style={styles.gallery}>{currentPhotos.length ? currentPhotos.map((photo) => <View key={photo.id} style={styles.photo}><Image source={{ uri: imageUri(photo.storage_path) }} style={styles.photoImage} /><View style={styles.photoBadge}><Text variant="microLabel" color={colors.textOnBrand}>{stage.toUpperCase()}</Text></View></View>) : <View style={styles.empty}><ImageIcon size={30} color={colors.textMuted} /><Text variant="bodyStrong">Nenhum registro nesta etapa</Text><Text variant="body" color={colors.textSecondary}>Adicione uma evidência pela câmera ou galeria.</Text></View>}</View><View style={styles.actions}><Pressable disabled={busy} onPress={() => { void addPhoto('camera'); }} style={styles.action}><View style={styles.actionIcon}><Camera size={22} color={colors.brand} /></View><Text variant="microLabel">CÂMERA</Text></Pressable><Pressable disabled={busy} onPress={() => { void addPhoto('gallery'); }} style={styles.action}><View style={styles.actionIcon}><ImageIcon size={22} color={colors.brand} /></View><Text variant="microLabel">GALERIA</Text></Pressable><Pressable disabled={busy} onPress={() => setStage('durante')} style={styles.action}><View style={styles.actionIcon}><Plus size={22} color={colors.brand} /></View><Text variant="microLabel">ADICIONAR</Text></Pressable></View><View style={styles.field}><Text variant="microLabel" color={colors.textMuted}>OBSERVAÇÕES DO REGISTRO</Text><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Adicione notas sobre o registro fotográfico..." placeholderTextColor={colors.slate300} style={styles.notes} /></View>{error ? <Text variant="body" color={colors.dangerStrong} style={styles.error}>{error}</Text> : null}<Button label="SALVAR REGISTRO" icon={Save} loading={busy} onPress={() => { void save(); }} /></ScrollView>}</View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bgApp }, header: { backgroundColor: colors.brandStrong, borderBottomLeftRadius: 40, borderBottomRightRadius: 40, paddingHorizontal: layout.screenPadding, paddingBottom: spacing.xxl, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, back: { width: 42, height: 42, borderRadius: radius.lg, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' }, headerText: { flex: 1, gap: spacing.xs }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: layout.screenPadding, gap: spacing.lg }, tabs: { flexDirection: 'row', backgroundColor: colors.slate100, padding: 5, borderRadius: radius.xl, gap: 5 }, tab: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.lg }, tabActive: { backgroundColor: colors.bgSurface, ...elevation.card }, gallery: { minHeight: 240, gap: spacing.md }, photo: { height: 220, borderRadius: 28, overflow: 'hidden', backgroundColor: colors.slate100, borderWidth: 1, borderColor: colors.border, position: 'relative' }, photoImage: { width: '100%', height: '100%' }, photoBadge: { position: 'absolute', left: spacing.md, bottom: spacing.md, backgroundColor: colors.brandStrong, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radius.md }, empty: { minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, backgroundColor: colors.slate50, borderRadius: 28, borderWidth: 1, borderColor: colors.border }, actions: { flexDirection: 'row', gap: spacing.sm }, action: { flex: 1, minHeight: 96, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.bgSurface, borderRadius: radius.xl, alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, actionIcon: { width: 42, height: 42, borderRadius: radius.pill, backgroundColor: colors.brandTint, alignItems: 'center', justifyContent: 'center' }, field: { gap: spacing.sm }, notes: { minHeight: 108, backgroundColor: colors.bgSurface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, padding: spacing.md, color: colors.textPrimary, fontFamily: fonts.medium, fontSize: 14, textAlignVertical: 'top' }, error: { padding: spacing.md, backgroundColor: colors.dangerSoft, borderRadius: radius.md } });
